name: reprohealth_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 < 4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  avatar_stack: ^1.2.0
  cached_network_image: ^3.3.0
  date_picker_timeline: ^1.2.5
  device_preview: ^1.1.0
  dio: any
  dotted_border: ^2.1.0
  dropdown_model_list: ^1.1.6
  email_otp: ^2.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  just_the_tooltip: ^0.0.12
  open_file: ^3.3.2
  path_provider: ^2.1.1
  pdf: ^3.10.7
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_reprohealth.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/font/Roboto-Regular.ttf
# flutter_assets:
#   assets_path: assets/
#   output_path: lib/constant/
#   filename: assets_constants.dart
